name: jonfostbai
favicon: null
layout_spectrum: 0.25346017302945256
typography_spectrum: 0.688883708557114
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.45515526668168604
  lightness: 0.6236920340452343
  saturation: 0.21524984552524984
  rhythmicContrast: 0.9574211593717337
purpose: []
